### ISSUE TITLE
Crash on queued radio load

### ISSUE THREAD

**Issue by HerHde** [azlux/botamusique#108]
**Describe the bug**
Starting the bot with a queue containing a radio stream crashes with the following error:

```
[[...] INFO MainThread] library: rebuild directory cache
[[...] INFO MainThread] bot: load playlist from previous session
Traceback (most recent call last):
  File "mumbleBot.py", line 689, in <module>
    var.playlist.load()
  File "[...]/botamusique/media/playlist.py", line 199, in load
    music_wrapper = get_cached_wrapper_by_id(var.bot, item['id'], item['user'])
  File "[...]/botamusique/media/cache.py", line 243, in get_cached_wrapper_by_id
    item = var.cache.get_item_by_id(bot, id)
  File "[...]/botamusique/media/cache.py", line 32, in get_item_by_id
    item = self.fetch(bot, id)
  File "[...]/botamusique/media/cache.py", line 78, in fetch
    self[id] = dict_to_item(bot, music_dict)
  File "[...]/botamusique/media/item.py", line 35, in dict_to_item
    return item_loaders[type](bot, music_dict)
  File "[...]/botamusique/media/radio.py", line 97, in radio_item_loader
    return RadioItem(bot, "", "", _dict)
  File "[...]/botamusique/media/radio.py", line 120, in __init__
    super().__init__(bot, from_dict)
  File "[...]/botamusique/media/item.py", line 57, in __init__
    self.path = from_dict['path']
KeyError: 'path'
```

**Affected version**
22e705a469c1f54bf34cd4ddf0da6a15aa68838b,
d0d1f538a4706f54e84e58068664f998d8c96273 (my PR)

**To Reproduce**
1. Delete the database.db
1. Start the bot
1. In Mumble, add a radio with `!radio` or `!url http://jazz-wr04.ice.infomaniak.ch/jazz-wr04-128.mp3` e.g.
1. Shut down and restart the bot. It should fail as described.

**Expected behaviour**
Do not crash, handle the attributes correctly.

I will skip the last parts of the Template.

As I found another KeyError for a stream's duration, which I will try to reproduce next, I recommend to await the next issue before taking action.

Thank you!

**Comment by TerryGeng** [comment]
Investigating.

**Comment by TerryGeng** [comment]
Should be fixed. Please check.

**Comment by HerHde** [comment]
No, it did not fix the problem. Same stack trace. Please reopen this issue.

> As I found another KeyError for a stream's duration, which I will try to reproduce next, I recommend to await the next issue before taking action.

Sorry, to clarify: As I found multiple key errors regarding streams I would suggest to take further investigation in the handling of attributes. In specific I meant to wait for me posting issue #109 before solving this. Maybe you want to get down to a possible root of those problems upfront.

**Comment by TerryGeng** [comment]
Although they are all called 'KeyError' but they are from completely different modules of the code. I don't think there's any connection between this issue and #109.

**Comment by TerryGeng** [comment]
And since I'm in China, I'm not really keen on debugging youtube stuff. Playing radios is also painful. We are on freenode #mumble channel. You can find us there and help us speed up the debugging process.
