### ISSUE TITLE
YouTube playlist broken

### ISSUE THREAD

**Issue by TheFrenchGhosty** [azlux/botamusique#97]
**Describe the bug**
When sending a YouTube playlist URL to the bot, it will download it, then trigger an error, then download it again.

**Affected version**
Latest Git, [69c3fa2](https://github.com/azlux/botamusique/commit/69c3fa22e8f9c79948c985a0ac1eea177e322989)

**To Reproduce**
!url [Any Playlist Link]

**Log:**

```
[Mar 10 18:39:17 INFO MainThread] bot: botamusique version 5.2, starting...
[Mar 10 18:39:17 INFO MainThread] bot: load playlist from previous session
[Mar 10 18:39:53 INFO Thread-2] bot: received command url - <a href="https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6">https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6</a> by [USERNAME]
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[download] Downloading video 2 of 16
[youtube] RockJQdfDJI: Downloading webpage
[youtube] Downloading just video RockJQdfDJI because of --no-playlist
[download] Downloading video 3 of 16
[youtube] OiXjRNwZ8D0: Downloading webpage
[youtube] Downloading just video OiXjRNwZ8D0 because of --no-playlist
[download] Downloading video 4 of 16
[youtube] FY8VNtnCQpw: Downloading webpage
[youtube] Downloading just video FY8VNtnCQpw because of --no-playlist
[download] Downloading video 5 of 16
[youtube] ahgNt8QkbJg: Downloading webpage
[youtube] Downloading just video ahgNt8QkbJg because of --no-playlist
[download] Downloading video 6 of 16
[youtube] mv4XRZ9swlE: Downloading webpage
[youtube] Downloading just video mv4XRZ9swlE because of --no-playlist
[download] Downloading video 7 of 16
[youtube] 9Ck2QZJ3kQ0: Downloading webpage
[youtube] Downloading just video 9Ck2QZJ3kQ0 because of --no-playlist
[download] Downloading video 8 of 16
[youtube] 1Kk17OuJLqg: Downloading webpage
[youtube] Downloading just video 1Kk17OuJLqg because of --no-playlist
[download] Downloading video 9 of 16
[youtube] it0Uhdr2cvk: Downloading webpage
[youtube] Downloading just video it0Uhdr2cvk because of --no-playlist
[download] Downloading video 10 of 16
[youtube] Mn1KQbrzO48: Downloading webpage
[youtube] Downloading just video Mn1KQbrzO48 because of --no-playlist
[download] Downloading video 11 of 16
[youtube] lRekna8s8_g: Downloading webpage
[youtube] Downloading just video lRekna8s8_g because of --no-playlist
[download] Downloading video 12 of 16
[youtube] u3rh35F6v2s: Downloading webpage
[youtube] Downloading just video u3rh35F6v2s because of --no-playlist
[download] Downloading video 13 of 16
[youtube] B5M22aGgtMI: Downloading webpage
[youtube] Downloading just video B5M22aGgtMI because of --no-playlist
[download] Downloading video 14 of 16
[youtube] lzd3jvNbh60: Downloading webpage
[youtube] Downloading just video lzd3jvNbh60 because of --no-playlist
[download] Downloading video 15 of 16
[youtube] MBzuXXNGw2s: Downloading webpage
[youtube] Downloading just video MBzuXXNGw2s because of --no-playlist
[download] Downloading video 16 of 16
[youtube] 64MxqHMnkBc: Downloading webpage
[youtube] Downloading just video 64MxqHMnkBc because of --no-playlist
[download] Finished downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[Mar 10 18:40:47 INFO Thread-2] bot: verifying the duration of url https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6 
[Mar 10 18:40:47 INFO Thread-2] cmd: add to playlist: [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:40:47 INFO MainThread] bot: play music [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:40:47 INFO MainThread] bot: current music isn't ready, start downloading.
[Mar 10 18:40:47 INFO MainThread] bot: start downloading item in thread: [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:40:47 INFO MainThread] bot: start downloading item in thread: [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:40:47 INFO DownloadThread-8cc72] bot: downloading url (8cc7205482bbea47c25f8480a4faebaf) https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6 
[Mar 10 18:40:47 INFO DownloadThread-8cc72] bot: downloading url (8cc7205482bbea47c25f8480a4faebaf) https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6 
[Mar 10 18:40:47 INFO DownloadThread-8cc72] bot: download attempts 1 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[Mar 10 18:40:47 INFO DownloadThread-8cc72] bot: download attempts 1 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[youtube] NeHFBX8YLSc: Downloading thumbnail ...
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[youtube] NeHFBX8YLSc: Downloading thumbnail ...
[youtube] NeHFBX8YLSc: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] NeHFBX8YLSc: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.4% of 3.60MiB at Unknown speed ETA Unknown ETA[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.4% of 3.60MiB at 14.49MiB/s ETA 00:00
[K[download]   0.8% of 3.60MiB at  5.32MiB/s ETA 00:00
[K[download]   0.8% of 3.60MiB at  5.26MiB/s ETA 00:00
[K[download]   1.7% of 3.60MiB at  6.39MiB/s ETA 00:00
[K[download]   1.7% of 3.60MiB at  6.36MiB/s ETA 00:00
[K[download]   3.4% of 3.60MiB at  8.47MiB/s ETA 00:00
[K[download]   3.4% of 3.60MiB at  8.53MiB/s ETA 00:00
[K[download]   6.9% of 3.60MiB at 13.19MiB/s ETA 00:00
[K[download]   6.9% of 3.60MiB at 13.34MiB/s ETA 00:00
[K[download]  13.9% of 3.60MiB at 20.36MiB/s ETA 00:00
[K[download]  13.9% of 3.60MiB at 19.66MiB/s ETA 00:00
[K[download]  27.8% of 3.60MiB at 29.93MiB/s ETA 00:00
[K[download]  27.8% of 3.60MiB at 28.93MiB/s ETA 00:00
[K[download]  55.6% of 3.60MiB at 38.07MiB/s ETA 00:00
[K[download]  55.6% of 3.60MiB at 37.51MiB/s ETA 00:00
[K[download] 100.0% of 3.60MiB at 36.44MiB/s ETA 00:00
[K[download] 100% of 3.60MiB in 00:03

[K[download] 100.0% of 3.60MiB at 35.41MiB/s ETA 00:00[0;31mERROR:[0m unable to rename file: [Errno 2] No such file or directory: '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a.part' -> '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a'
[Mar 10 18:40:59 ERROR DownloadThread-8cc72] bot: download failed with error:
 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a.part' -> '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a'
[Mar 10 18:40:59 INFO DownloadThread-8cc72] bot: download attempts 2 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 2 of 16
[youtube] RockJQdfDJI: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[youtube] Downloading just video RockJQdfDJI because of --no-playlist
[youtube] RockJQdfDJI: Downloading thumbnail ...
[youtube] RockJQdfDJI: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[youtube] NeHFBX8YLSc: Downloading thumbnail ...
[youtube] NeHFBX8YLSc: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.5% of 2.86MiB at 14.12MiB/s ETA 00:00
[K[download]   1.1% of 2.86MiB at  5.02MiB/s ETA 00:00
[K[download]   2.2% of 2.86MiB at  6.05MiB/s ETA 00:00
[K[download]   4.3% of 2.86MiB at  8.07MiB/s ETA 00:00
[K[download]   8.7% of 2.86MiB at 12.69MiB/s ETA 00:00
[K[download]  17.5% of 2.86MiB at 19.61MiB/s ETA 00:00
[K[download]  35.0% of 2.86MiB at 31.50MiB/s ETA 00:00
[K[download]  70.0% of 2.86MiB at 26.79MiB/s ETA 00:00
[K[download] 100.0% of 2.86MiB at 34.77MiB/s ETA 00:00
[K[download] 100% of 2.86MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 3 of 16
[youtube] OiXjRNwZ8D0: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.60MiB at  6.81MiB/s ETA 00:00
[K[download]   0.4% of 3.60MiB at 13.67MiB/s ETA 00:00
[K[download]   0.8% of 3.60MiB at  5.32MiB/s ETA 00:00
[K[download]   1.7% of 3.60MiB at  6.39MiB/s ETA 00:00
[K[download]   3.4% of 3.60MiB at  8.54MiB/s ETA 00:00
[K[download]   6.9% of 3.60MiB at 13.40MiB/s ETA 00:00
[K[download]  13.9% of 3.60MiB at 21.01MiB/s ETA 00:00
[K[download]  27.8% of 3.60MiB at 33.51MiB/s ETA 00:00
[K[download]  55.6% of 3.60MiB at 43.40MiB/s ETA 00:00
[K[download] 100.0% of 3.60MiB at 54.16MiB/s ETA 00:00
[K[download] 100% of 3.60MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
[youtube] Downloading just video OiXjRNwZ8D0 because of --no-playlist
[youtube] OiXjRNwZ8D0: Downloading thumbnail ...
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 2 of 16
[youtube] RockJQdfDJI: Downloading webpage
[youtube] OiXjRNwZ8D0: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] Downloading just video RockJQdfDJI because of --no-playlist
[youtube] RockJQdfDJI: Downloading thumbnail ...
[youtube] RockJQdfDJI: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 2.95MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 2.95MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 2.95MiB at  6.52MiB/s ETA 00:00
[K[download]   0.5% of 2.95MiB at 12.94MiB/s ETA 00:00
[K[download]   1.0% of 2.95MiB at  5.22MiB/s ETA 00:00
[K[download]   2.1% of 2.95MiB at  6.21MiB/s ETA 00:00
[K[download]   4.2% of 2.95MiB at  8.33MiB/s ETA 00:00
[K[download]   8.4% of 2.95MiB at 13.14MiB/s ETA 00:00
[K[download]  16.9% of 2.95MiB at 20.68MiB/s ETA 00:00
[K[download]  33.9% of 2.95MiB at 33.21MiB/s ETA 00:00
[K[download]  67.8% of 2.95MiB at 50.79MiB/s ETA 00:00
[K[download] 100.0% of 2.95MiB at 31.16MiB/s ETA 00:00
[K[download] 100% of 2.95MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 4 of 16
[youtube] FY8VNtnCQpw: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.5% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   1.1% of 2.86MiB at  5.66MiB/s ETA 00:00
[K[download]   2.2% of 2.86MiB at  6.43MiB/s ETA 00:00
[K[download]   4.3% of 2.86MiB at  8.48MiB/s ETA 00:00
[K[download]   8.7% of 2.86MiB at 13.17MiB/s ETA 00:00
[K[download]  17.5% of 2.86MiB at 20.33MiB/s ETA 00:00
[K[download]  35.0% of 2.86MiB at 33.26MiB/s ETA 00:00
[K[download]  70.0% of 2.86MiB at 50.79MiB/s ETA 00:00
[K[download] 100.0% of 2.86MiB at 53.24MiB/s ETA 00:00
[K[download] 100% of 2.86MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 3 of 16
[youtube] OiXjRNwZ8D0: Downloading webpage
[youtube] Downloading just video FY8VNtnCQpw because of --no-playlist
[youtube] FY8VNtnCQpw: Downloading thumbnail ...
[youtube] Downloading just video OiXjRNwZ8D0 because of --no-playlist
[youtube] OiXjRNwZ8D0: Downloading thumbnail ...
[youtube] FY8VNtnCQpw: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] OiXjRNwZ8D0: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.62MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.62MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.62MiB at Unknown speed ETA Unknown ETA
[K[download]   0.4% of 3.62MiB at 14.06MiB/s ETA 00:00
[K[download]   0.8% of 3.62MiB at  5.14MiB/s ETA 00:00
[K[download]   1.7% of 3.62MiB at  6.01MiB/s ETA 00:00
[K[download]   3.4% of 3.62MiB at  8.08MiB/s ETA 00:00
[K[download]   6.9% of 3.62MiB at 12.87MiB/s ETA 00:00[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 2.95MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 2.95MiB at  2.90MiB/s ETA 00:01
[K[download]   0.2% of 2.95MiB at  6.13MiB/s ETA 00:00
[K[download]   0.5% of 2.95MiB at 12.17MiB/s ETA 00:00
[K[download]  13.8% of 3.62MiB at 20.15MiB/s ETA 00:00
[K[download]   1.0% of 2.95MiB at  4.58MiB/s ETA 00:00
[K[download]   2.1% of 2.95MiB at  5.63MiB/s ETA 00:00
[K[download]  27.6% of 3.62MiB at 32.35MiB/s ETA 00:00
[K[download]   4.2% of 2.95MiB at  6.16MiB/s ETA 00:00
[K[download]  55.2% of 3.62MiB at 48.85MiB/s ETA 00:00
[K[download]   8.4% of 2.95MiB at 11.34MiB/s ETA 00:00
[K[download]  16.9% of 2.95MiB at 16.10MiB/s ETA 00:00
[K[download]  33.9% of 2.95MiB at 25.75MiB/s ETA 00:00
[K[download]  67.8% of 2.95MiB at 41.49MiB/s ETA 00:00
[K[download] 100.0% of 2.95MiB at 39.82MiB/s ETA 00:00
[K[download] 100% of 2.95MiB in 00:03

[K[download] 100.0% of 3.62MiB at 29.53MiB/s ETA 00:00[0;31mERROR:[0m unable to rename file: [Errno 2] No such file or directory: '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a.part' -> '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a'
[Mar 10 18:41:31 ERROR DownloadThread-8cc72] bot: download failed with error:
 FileNotFoundError: [Errno 2] No such file or directory: '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a.part' -> '/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a'
[Mar 10 18:41:31 INFO DownloadThread-8cc72] bot: download attempts 2 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 4 of 16
[youtube] FY8VNtnCQpw: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[youtube] Downloading just video FY8VNtnCQpw because of --no-playlist
[youtube] FY8VNtnCQpw: Downloading thumbnail ...
[youtube] FY8VNtnCQpw: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[youtube] NeHFBX8YLSc: Downloading thumbnail ...
[youtube] NeHFBX8YLSc: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.62MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.62MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.62MiB at Unknown speed ETA Unknown ETA
[K[download]   0.4% of 3.62MiB at 13.94MiB/s ETA 00:00
[K[download]   0.8% of 3.62MiB at  5.27MiB/s ETA 00:00
[K[download]   1.7% of 3.62MiB at  6.21MiB/s ETA 00:00
[K[download]   3.4% of 3.62MiB at  8.31MiB/s ETA 00:00
[K[download]   6.9% of 3.62MiB at 13.39MiB/s ETA 00:00
[K[download]  13.8% of 3.62MiB at 20.62MiB/s ETA 00:00
[K[download]  27.6% of 3.62MiB at 33.04MiB/s ETA 00:00
[K[download]  55.2% of 3.62MiB at 46.93MiB/s ETA 00:00
[K[download] 100.0% of 3.62MiB at 58.12MiB/s ETA 00:00
[K[download] 100% of 3.62MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 5 of 16
[youtube] ahgNt8QkbJg: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.4% of 3.60MiB at 14.48MiB/s ETA 00:00
[K[download]   0.8% of 3.60MiB at  5.35MiB/s ETA 00:00
[K[download]   1.7% of 3.60MiB at  6.23MiB/s ETA 00:00
[K[download]   3.4% of 3.60MiB at  8.38MiB/s ETA 00:00
[K[download]   6.9% of 3.60MiB at 13.24MiB/s ETA 00:00
[K[download]  13.9% of 3.60MiB at 20.78MiB/s ETA 00:00
[K[download]  27.8% of 3.60MiB at 33.29MiB/s ETA 00:00
[K[download]  55.6% of 3.60MiB at 37.98MiB/s ETA 00:00
[K[download] 100.0% of 3.60MiB at 63.27MiB/s ETA 00:00
[K[download] 100% of 3.60MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
[youtube] Downloading just video ahgNt8QkbJg because of --no-playlist
[youtube] ahgNt8QkbJg: Downloading thumbnail ...
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 2 of 16
[youtube] RockJQdfDJI: Downloading webpage
[youtube] ahgNt8QkbJg: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] Downloading just video RockJQdfDJI because of --no-playlist
[youtube] RockJQdfDJI: Downloading thumbnail ...
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.28MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.28MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.28MiB at  6.46MiB/s ETA 00:00
[K[download]   0.4% of 3.28MiB at 12.87MiB/s ETA 00:00[youtube] RockJQdfDJI: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Resuming download at byte 15360

[K[download]   0.9% of 3.28MiB at  5.50MiB/s ETA 00:00
[K[download]   1.9% of 3.28MiB at  6.17MiB/s ETA 00:00
[K[download]   3.8% of 3.28MiB at  8.01MiB/s ETA 00:00
[K[download]   7.6% of 3.28MiB at 12.48MiB/s ETA 00:00
[K[download]  15.2% of 3.28MiB at 19.20MiB/s ETA 00:00
[K[download]  30.5% of 3.28MiB at 30.91MiB/s ETA 00:00
[K[download]  61.0% of 3.28MiB at 20.04MiB/s ETA 00:00
[K[download] 100.0% of 3.28MiB at 27.22MiB/s ETA 00:00
[K[download] 100% of 3.28MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 6 of 16
[youtube] mv4XRZ9swlE: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.5% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.6% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.8% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   1.0% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   1.6% of 2.86MiB at  6.10MiB/s ETA 00:00
[K[download]   2.7% of 2.86MiB at  6.57MiB/s ETA 00:00
[K[download]   4.9% of 2.86MiB at  8.25MiB/s ETA 00:00
[K[download]   9.2% of 2.86MiB at 12.82MiB/s ETA 00:00
[K[download]  18.0% of 2.86MiB at 20.25MiB/s ETA 00:00
[K[download]  35.5% of 2.86MiB at 32.46MiB/s ETA 00:00
[K[download]  70.5% of 2.86MiB at 44.76MiB/s ETA 00:00
[K[download] 100.0% of 2.86MiB at 59.19MiB/s ETA 00:00
[K[download] 100% of 2.86MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[0;31mERROR:[0m file:/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a: Invalid data found when processing input
[Mar 10 18:41:53 ERROR DownloadThread-8cc72] bot: download failed with error:
 youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a: Invalid data found when processing input
[Mar 10 18:41:53 INFO MainThread] bot: play music [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:41:53 INFO MainThread] bot: current music isn't ready, start downloading.
[Mar 10 18:41:53 INFO MainThread] bot: start downloading item in thread: [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:41:53 INFO DownloadThread-8cc72] bot: downloading url (8cc7205482bbea47c25f8480a4faebaf) https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6 
[Mar 10 18:41:53 INFO DownloadThread-8cc72] bot: download attempts 1 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[youtube] Downloading just video mv4XRZ9swlE because of --no-playlist
[youtube] mv4XRZ9swlE: Downloading thumbnail ...
[youtube] mv4XRZ9swlE: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.27MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.27MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.27MiB at Unknown speed ETA Unknown ETA
[K[download]   0.4% of 3.27MiB at Unknown speed ETA Unknown ETA
[K[download]   0.9% of 3.27MiB at  5.09MiB/s ETA 00:00
[K[download]   1.9% of 3.27MiB at  6.10MiB/s ETA 00:00
[K[download]   3.8% of 3.27MiB at  8.20MiB/s ETA 00:00
[K[download]   7.6% of 3.27MiB at 12.76MiB/s ETA 00:00
[K[download]  15.2% of 3.27MiB at 19.99MiB/s ETA 00:00
[K[download]  30.5% of 3.27MiB at 32.19MiB/s ETA 00:00
[K[download]  61.1% of 3.27MiB at 49.56MiB/s ETA 00:00
[K[download] 100.0% of 3.27MiB at 45.37MiB/s ETA 00:00
[K[download] 100% of 3.27MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[youtube] NeHFBX8YLSc: Downloading thumbnail ...
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 7 of 16
[youtube] 9Ck2QZJ3kQ0: Downloading webpage
[youtube] NeHFBX8YLSc: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] Downloading just video 9Ck2QZJ3kQ0 because of --no-playlist
[youtube] 9Ck2QZJ3kQ0: Downloading thumbnail ...
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.60MiB at  2.77MiB/s ETA 00:01
[K[download]   0.2% of 3.60MiB at  6.04MiB/s ETA 00:00
[K[download]   0.4% of 3.60MiB at 12.16MiB/s ETA 00:00
[K[download]   0.8% of 3.60MiB at  4.96MiB/s ETA 00:00
[K[download]   1.7% of 3.60MiB at  6.08MiB/s ETA 00:00[youtube] 9Ck2QZJ3kQ0: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Resuming download at byte 64512

[K[download]   3.4% of 3.60MiB at  8.08MiB/s ETA 00:00
[K[download]   6.9% of 3.60MiB at 12.72MiB/s ETA 00:00
[K[download]  13.9% of 3.60MiB at 19.77MiB/s ETA 00:00
[K[download]  27.8% of 3.60MiB at 31.62MiB/s ETA 00:00
[K[download]  55.6% of 3.60MiB at 48.81MiB/s ETA 00:00
[K[download] 100.0% of 3.60MiB at 31.57MiB/s ETA 00:00
[K[download] 100% of 3.60MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 2 of 16
[youtube] RockJQdfDJI: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   1.7% of 3.63MiB at Unknown speed ETA Unknown ETA
[K[download]   1.8% of 3.63MiB at Unknown speed ETA Unknown ETA
[K[download]   1.9% of 3.63MiB at Unknown speed ETA Unknown ETA
[K[download]   2.1% of 3.63MiB at 14.54MiB/s ETA 00:00
[K[download]   2.5% of 3.63MiB at  5.17MiB/s ETA 00:00
[K[download]   3.4% of 3.63MiB at  6.07MiB/s ETA 00:00
[K[download]   5.1% of 3.63MiB at  8.09MiB/s ETA 00:00
[K[download]   8.5% of 3.63MiB at 12.76MiB/s ETA 00:00
[K[download]  15.4% of 3.63MiB at 19.68MiB/s ETA 00:00
[K[download]  29.2% of 3.63MiB at 31.70MiB/s ETA 00:00
[K[download]  56.7% of 3.63MiB at 41.88MiB/s ETA 00:00
[K[download] 100.0% of 3.63MiB at 52.26MiB/s ETA 00:00
[K[download] 100% of 3.63MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[0;31mERROR:[0m   Stream #0:0 -> #0:0 (copy)
[Mar 10 18:42:09 ERROR DownloadThread-8cc72] bot: download failed with error:
 youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError:   Stream #0:0 -> #0:0 (copy)
[Mar 10 18:42:09 INFO MainThread] bot: play music [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:42:09 INFO MainThread] bot: current music isn't ready, start downloading.
[Mar 10 18:42:09 INFO MainThread] bot: start downloading item in thread: [url] 8cc7205482bbea47c25f8480a4faebaf (https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6) by [USERNAME]
[Mar 10 18:42:09 INFO DownloadThread-8cc72] bot: downloading url (8cc7205482bbea47c25f8480a4faebaf) https://www.youtube.com/playlist?list=PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6 
[Mar 10 18:42:09 INFO DownloadThread-8cc72] bot: download attempts 1 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[youtube] Downloading just video RockJQdfDJI because of --no-playlist
[youtube] RockJQdfDJI: Downloading thumbnail ...
[youtube] RockJQdfDJI: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   0.5% of 2.86MiB at Unknown speed ETA Unknown ETA
[K[download]   1.1% of 2.86MiB at  5.36MiB/s ETA 00:00
[K[download]   2.2% of 2.86MiB at  6.25MiB/s ETA 00:00
[K[download]   4.3% of 2.86MiB at  8.37MiB/s ETA 00:00
[K[download]   8.7% of 2.86MiB at 13.03MiB/s ETA 00:00
[K[download]  17.5% of 2.86MiB at 20.26MiB/s ETA 00:00
[K[download]  35.0% of 2.86MiB at 32.33MiB/s ETA 00:00
[K[download]  70.0% of 2.86MiB at 49.63MiB/s ETA 00:00
[K[download] 100.0% of 2.86MiB at 52.62MiB/s ETA 00:00
[K[download] 100% of 2.86MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
[youtube] Downloading just video NeHFBX8YLSc because of --no-playlist
[youtube] NeHFBX8YLSc: Downloading thumbnail ...
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 3 of 16
[youtube] OiXjRNwZ8D0: Downloading webpage
[youtube] NeHFBX8YLSc: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[youtube] Downloading just video OiXjRNwZ8D0 because of --no-playlist
[youtube] OiXjRNwZ8D0: Downloading thumbnail ...
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   0.0% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.1% of 3.60MiB at Unknown speed ETA Unknown ETA
[K[download]   0.2% of 3.60MiB at  6.53MiB/s ETA 00:00
[K[download]   0.4% of 3.60MiB at 13.11MiB/s ETA 00:00
[K[download]   0.8% of 3.60MiB at  5.07MiB/s ETA 00:00[youtube] OiXjRNwZ8D0: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] Resuming download at byte 31744

[K[download]   1.7% of 3.60MiB at  6.10MiB/s ETA 00:00
[K[download]   3.4% of 3.60MiB at  7.97MiB/s ETA 00:00
[K[download]   6.9% of 3.60MiB at 12.53MiB/s ETA 00:00
[K[download]  13.9% of 3.60MiB at 19.55MiB/s ETA 00:00
[K[download]  27.8% of 3.60MiB at 31.39MiB/s ETA 00:00
[K[download]  55.6% of 3.60MiB at 48.52MiB/s ETA 00:00
[K[download] 100.0% of 3.60MiB at 31.77MiB/s ETA 00:00
[K[download] 100% of 3.60MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[ffmpeg] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.mp3
Deleting original file /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a (pass -k to keep)
[ffmpeg] Adding metadata to '/tmp/8cc7205482bbea47c25f8480a4faebaf.mp3'
[download] Downloading video 2 of 16
[youtube] RockJQdfDJI: Downloading webpage
[download] Destination: /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a

[K[download]   1.1% of 2.95MiB at Unknown speed ETA Unknown ETA
[K[download]   1.1% of 2.95MiB at Unknown speed ETA Unknown ETA
[K[download]   1.3% of 2.95MiB at Unknown speed ETA Unknown ETA
[K[download]   1.5% of 2.95MiB at 14.46MiB/s ETA 00:00
[K[download]   2.1% of 2.95MiB at  5.00MiB/s ETA 00:00
[K[download]   3.1% of 2.95MiB at  5.98MiB/s ETA 00:00
[K[download]   5.2% of 2.95MiB at  7.95MiB/s ETA 00:00
[K[download]   9.5% of 2.95MiB at 12.51MiB/s ETA 00:00
[K[download]  17.9% of 2.95MiB at 19.52MiB/s ETA 00:00
[K[download]  34.9% of 2.95MiB at 31.79MiB/s ETA 00:00
[K[download]  68.8% of 2.95MiB at 24.16MiB/s ETA 00:00
[K[download] 100.0% of 2.95MiB at 22.39MiB/s ETA 00:00
[K[download] 100% of 2.95MiB in 00:03
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[0;31mERROR:[0m file:/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a: Invalid data found when processing input
[Mar 10 18:42:25 ERROR DownloadThread-8cc72] bot: download failed with error:
 youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a: Invalid data found when processing input
[Mar 10 18:42:25 INFO DownloadThread-8cc72] bot: download attempts 2 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[youtube] Downloading just video RockJQdfDJI because of --no-playlist
[youtube] RockJQdfDJI: Downloading thumbnail ...
[youtube] RockJQdfDJI: Writing thumbnail to: /tmp/8cc7205482bbea47c25f8480a4faebaf.jpg
[download] /tmp/8cc7205482bbea47c25f8480a4faebaf.m4a has already been downloaded

[K[download] 100% of 2.92MiB
[ffmpeg] Correcting container in "/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a"
[0;31mERROR:[0m file:/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a: Invalid data found when processing input
[Mar 10 18:42:28 ERROR DownloadThread-8cc72] bot: download failed with error:
 youtube_dl.postprocessor.ffmpeg.FFmpegPostProcessorError: file:/tmp/8cc7205482bbea47c25f8480a4faebaf.m4a: Invalid data found when processing input
[Mar 10 18:42:28 INFO DownloadThread-8cc72] bot: download attempts 2 / 2
[youtube:playlist] PLx4KuU4ZoA_dIdG4Uqlm5GNGyHqgZqNv6: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
[download] Downloading playlist: The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia
[youtube:playlist] playlist The Groove Sessions Vol. 5 - Chinese Man, Scratch Bandits Crew, Baja Frequencia: Downloading 16 videos
[download] Downloading video 1 of 16
[youtube] NeHFBX8YLSc: Downloading webpage
```

**Comment by TerryGeng** [comment]
Hi. Did you see the "No such file or directory "error in the log? I think that's caused by some permission issue. 

You can try just play an YouTube URL by the '!URL command first. If you got the same problem as well, then please have a look on the permission settings on your /tmp folder.

**Comment by TerryGeng** [comment]
One more thing, if you want to add an entire YouTube playlist to the bot, please use !Playlist command.

However, this should have nothing to do with this error.

**Comment by TheFrenchGhosty** [comment]
>You can try just play an YouTube URL by the '!URL command first. If you got the same problem as well, then please have a look on the permission settings on your /tmp folder.

This does work correctly with a video URL, the problem is only here with playlist, so I don't think it's a permission issue.

**Comment by TerryGeng** [comment]
Since this error occurs in youtube-dl, I think this is something wrong with your youtube-dl. You can try to update your youtube-dl to its newest version, you can also try to report this bug to youtube-dl https://github.com/ytdl-org/youtube-dl.

In the coming release of next botamusique, the bot will delete failed song from the playlist so you won't see the bot keep trying on items the failed.

**Comment by TheFrenchGhosty** [comment]
>Since this error occurs in youtube-dl, I think this is something wrong with your youtube-dl. You can try to update your youtube-dl to its newest version, you can also try to report this bug to youtube-dl https://github.com/ytdl-org/youtube-dl.

It's already the latest version sadly.

>In the coming release of next botamusique, the bot will delete failed song from the playlist so you won't see the bot keep trying on items the failed.

Should fix the problem.

**Comment by TerryGeng** [comment]
Hi, it has been some days and does this problem persist? Can I close this issue?

**Comment by TheFrenchGhosty** [comment]
Looks like it's fixed in 6.0.

Closing.
